const ProductData = [
    {
      id: 1,
      title: "Galaxy Tab S6 Lite 10.4-inch Android Tablet 128GB.",
      name: "Tablet",
      price: 72,
      img: "./img/tp1.jpg",
    },
    {
      id: 2,
      title: "Tracker with IP67 Waterproof Pedometer Smart watch.",
      name: "Smart Watch",
      price: 16,
      img: "./img/tp2.jpg",
    },
    {
      id: 3,
      title: "Cancelling Headphones Wireless is available.",
      name: "Headphone",
      price: 49,
      img: "./img/tp3.jpg",
    },
    {
      id: 4,
      title: "Professional Camera 4K Digital Video Camera.",
      name: "Camera",
      price: 200,
      img: "./img/tp4.jpg",
    },
    {
      id: 5,
      title: "Mini Portable PD 22.5W Fast Charging Powerbank.",
      name: "Powerbank",
      price: 49,
      img: "./img/tp5.jpg",
    },
    {
      id: 6,
      title: "CPU Cooler 2 Heat Pipes 12mm 4 Pin PWM RGB for Intel.",
      name: "Heat pipe",
      price: 15,
      img: "./img/tp6.png",
    },
    {
      id: 7,
      title: "Playstation 4 2TB Slim Gaming the  Console.",
      name: "Gaming",
      price: 20,
      img: "./img/tp7.jpg",
    },
    {
      id: 8,
      title: "Mini Portable Mobile Phone Powerbank for iphone.",
      name: "Mobile",
      price: 38,
      img: "./img/tp8.jpg",
    },
    {
      id: 9,
      title: "Mini Portable Mobile Phone Powerbank for iphone.",
      name: "Tablet",
      price: 38,
      img: "./img/p9.jpg",
    },
    {
      id: 10,
      title: "CPU Cooler 2 Heat Pipes 12mm 4 Pin PWM RGB for Intel.",
      name: "Heat pipe",
      price: 15,
      img: "./img/p10.jpg",
    },
    {
      id: 11,
      title: "Mini Portable PD 22.5W Fast Charging Powerbank.",
      name: "Powerbank",
      price: 49,
      img: "./img/p11.jpg",
    },
  ];

  export default ProductData